"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowUpRight, Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, Clock3, FileText, Inbox, LayoutDashboard, Menu, MessageSquareText, MoreHorizontal, Phone, Plus, Search, Settings, ShieldCheck, Sparkles, UserRoundCheck, Users, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Application = { id:string; name:string; initials:string; role:string; source:string; received:string; owner:string; status:string; nextAction:string; due:string; lastContact:string; acknowledged:boolean; tone:string };

const applications: Application[] = [
 {id:"DEMO-0142",name:"Demo Candidate 01",initials:"D1",role:"Sales Development Representative",source:"LinkedIn",received:"Today, 9:42 AM",owner:"Recruiter A",status:"New application",nextAction:"Review application",due:"Today, 4:00 PM",lastContact:"Not yet contacted",acknowledged:false,tone:"violet"},
 {id:"DEMO-0141",name:"Demo Candidate 02",initials:"D2",role:"Medical Biller – Orthopedic",source:"JobStreet",received:"Today, 8:15 AM",owner:"Unassigned",status:"New application",nextAction:"Assign recruiter",due:"Overdue 1h",lastContact:"Auto-acknowledged 8:16 AM",acknowledged:true,tone:"blue"},
 {id:"DEMO-0138",name:"Demo Candidate 03",initials:"D3",role:"Property Investment Assistant",source:"Google Forms",received:"Yesterday, 3:28 PM",owner:"Recruiter B",status:"Phone screening",nextAction:"Send pre-call message",due:"Today, 2:30 PM",lastContact:"Yesterday, 4:02 PM",acknowledged:true,tone:"orange"},
 {id:"DEMO-0134",name:"Demo Candidate 04",initials:"D4",role:"Digital Marketing Associate",source:"Referral",received:"Aug 23, 11:05 AM",owner:"Recruiter C",status:"Awaiting client feedback",nextAction:"Send holding update",due:"Overdue 6h",lastContact:"Aug 23, 3:40 PM",acknowledged:true,tone:"green"},
 {id:"DEMO-0127",name:"Demo Candidate 05",initials:"D5",role:"Client Services Coordinator",source:"Facebook",received:"Aug 22, 7:50 PM",owner:"Recruiter A",status:"Interview scheduled",nextAction:"Buddy review invite",due:"Today, 5:00 PM",lastContact:"Yesterday, 10:14 AM",acknowledged:true,tone:"pink"},
];

const nav = [
 ["Dashboard",LayoutDashboard],["Application Inbox",Inbox],["Referrals",UserRoundCheck],["Candidates",Users],["Vacancies",BriefcaseBusiness],["Interviews",CalendarDays],["Communications",MessageSquareText],["Active Pool",UserRoundCheck],["Offers",FileText],["Onboarding Documents",ShieldCheck],["Recruitment Tasks",Check],["Team Performance",Sparkles],["Reports",ArrowUpRight],["Templates & Settings",Settings]
] as const;

export default function Page(){
 const router=useRouter(); const [active,setActive]=useState("Dashboard"); const [query,setQuery]=useState(""); const [status,setStatus]=useState("All statuses"); const [callCandidate,setCallCandidate]=useState<Application|null>(null); const [selectedCandidate,setSelectedCandidate]=useState<Application|null>(null); const [workflowItem,setWorkflowItem]=useState<{module:string;row:string[]}|null>(null); const [purpose,setPurpose]=useState(""); const [messageSent,setMessageSent]=useState(false); const [ack,setAck]=useState(false); const [scheduled,setScheduled]=useState(""); const [mobile,setMobile]=useState(false); const [liveApplications,setLiveApplications]=useState<Application[]>([]); const [dataReady,setDataReady]=useState(false); const [profile,setProfile]=useState({full_name:"Recruiter",job_title:"Recruitment Team"});
 useEffect(()=>{let mounted=true;async function load(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const {data:member}=await supabase.from("team_members").select("full_name, job_title, active").eq("id",user.id).maybeSingle();if(!member?.active){await supabase.auth.signOut();router.replace("/login?access=denied");return}if(mounted)setProfile({full_name:member.full_name,job_title:member.job_title||"Recruitment Team"});const {data}=await supabase.from("application_overview").select("*").order("next_action_due",{ascending:true,nullsFirst:false});if(mounted&&data){setLiveApplications(data.map((row,index)=>({id:row.application_code,name:row.candidate_name,initials:initials(row.candidate_name),role:row.position_title,source:row.source,received:"Received",owner:row.owner_name||"Unassigned",status:row.status,nextAction:row.next_action||"Set next action",due:formatDate(row.next_action_due),lastContact:formatDate(row.last_communication_at,"Not yet contacted"),acknowledged:Boolean(row.last_communication_at),tone:["violet","blue","orange","green","pink"][index%5]})));setDataReady(true)}}load();return()=>{mounted=false}},[router]);
 const source=liveApplications.length?liveApplications:applications;
 const filtered=useMemo(()=>source.filter(a=>(a.name+a.role+a.id).toLowerCase().includes(query.toLowerCase())&&(status==="All statuses"||a.status===status)),[query,status,source]);
 const canCall=purpose&&messageSent&&scheduled;
 return <div className="shell">
  <aside className={mobile?"sidebar open":"sidebar"}>
   <div className="brand"><div className="brandmark">S</div><div><b>Scale Up</b><span>Recruitment Hub</span></div><button className="closeMobile" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"nav active":"nav"} onClick={()=>{setActive(label);setMobile(false)}}><Icon size={18}/><span>{label}</span>{label==="Application Inbox"&&<em>8</em>}</button>)}</nav>
   <div className="profile"><div className="avatar">{initials(profile.full_name)}</div><div><b>{profile.full_name}</b><span>{profile.job_title}</span></div><MoreHorizontal size={18}/></div>
  </aside>
  {mobile&&<div className="shade" onClick={()=>setMobile(false)}/>} 
  <main>
   <header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Search candidates, roles, or reference…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="iconBtn"><Bell size={19}/><i/></button><button className="primary" onClick={()=>setActive("Application Inbox")}><Plus size={18}/> New application</button></header>
   <div className="content">
    <section className="welcome"><div><p>Tuesday, August 25</p><h1>Good morning, {profile.full_name.split(" ")[0]} <span>👋</span></h1><h2>Here’s what needs your attention today.</h2></div><button className="outline" onClick={()=>setActive("Recruitment Tasks")}><Sparkles size={17}/> View my priorities</button></section>
    {active==="Dashboard"&&<><section className="alerts">
     <Alert title="Unacknowledged" count="3" note="Oldest waiting 2h 18m" kind="red" icon={<Inbox/>}/>
     <Alert title="Missing next action" count="5" note="Requires assignment" kind="amber" icon={<AlertTriangle/>}/>
     <Alert title="Updates overdue" count="7" note="No update within 48h" kind="purple" icon={<Clock3/>}/>
     <Alert title="Awaiting buddy review" count="2" note="Next interview at 5 PM" kind="blue" icon={<CalendarDays/>}/>
    </section>
    <section className="grid">
     <div className="panel applications"><div className="panelHead"><div><h3>Application inbox</h3><p>Prioritized by SLA and next-action date</p></div><button className="link" onClick={()=>setActive("Application Inbox")}>View all <ArrowUpRight size={15}/></button></div>
      <div className="filters"><div className="miniSearch"><Search size={16}/><input placeholder="Search applications" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="select"><select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option>{[...new Set(source.map(a=>a.status))].map(s=><option key={s}>{s}</option>)}</select><ChevronDown size={15}/></div><span className="connectionState"><i/>{dataReady?"Supabase connected":"Connecting…"}</span></div>
      <div className="tableWrap"><table><thead><tr><th>Candidate</th><th>Status</th><th>Owner</th><th>Next action</th><th>Last contact</th><th></th></tr></thead><tbody>{filtered.map(a=><tr key={a.id} className={!a.acknowledged?"urgent":""} onClick={()=>setSelectedCandidate(a)} style={{cursor:"pointer"}}><td><div className="candidate"><span className={`person ${a.tone}`}>{a.initials}</span><div><b>{a.name}</b><small>{a.role}</small><small>{a.source} · {a.id}</small></div></div></td><td><span className="statusDot">{a.status}</span></td><td><span className={a.owner==="Unassigned"?"unassigned":""}>{a.owner}</span></td><td><button className="action" onClick={e=>{e.stopPropagation();setCallCandidate(a)}}>{a.nextAction}<small className={a.due.includes("Overdue")?"overdue":""}>{a.due}</small></button></td><td><span className={!a.acknowledged?"noContact":""}>{a.lastContact}</span></td><td><button className="dots" onClick={e=>{e.stopPropagation();setSelectedCandidate(a)}}><MoreHorizontal/></button></td></tr>)}</tbody></table></div>
     </div>
     <aside className="rightcol">
      <div className="panel"><div className="panelHead"><div><h3>Today’s workload</h3><p>Your assigned priorities</p></div></div><div className="workload"><Ring/><div className="legend"><p><i className="l1"/>Screenings <b>4</b></p><p><i className="l2"/>Follow-ups <b>6</b></p><p><i className="l3"/>Interviews <b>2</b></p><p><i className="l4"/>Reviews <b>3</b></p></div></div><button className="full" onClick={()=>setActive("Recruitment Tasks")}>Open my task list</button></div>
      <div className="panel attention"><div className="panelHead"><div><h3>Needs attention</h3><p>Operational risks</p></div></div><Attention icon={<BriefcaseBusiness/>} title="2 filled vacancies" text="Still have active job posts"/><Attention icon={<ShieldCheck/>} title="1 early document request" text="Sensitive document policy flag"/><Attention icon={<Users/>} title="3 active-pool follow-ups" text="30-day reconfirmation overdue"/></div>
     </aside>
    </section></>}
    {active!=="Dashboard"&&<DemoModule name={active} applications={filtered} onCandidate={setSelectedCandidate} onCall={setCallCandidate} onOpen={(row)=>setWorkflowItem({module:active,row})}/>} 
   </div>
  </main>
  {callCandidate&&<div className="modalBackdrop"><div className="modal"><button className="modalClose" onClick={()=>setCallCandidate(null)}><X/></button><div className="modalIcon"><Phone/></div><p className="eyebrow">MESSAGE-FIRST CALL</p><h2>Prepare call with {callCandidate.name}</h2><div className="ownership"><AlertTriangle size={18}/><p>This candidate is currently assigned to <b>{callCandidate.owner}</b>. Last communication was on <b>{callCandidate.lastContact}</b>.</p></div><label>Call purpose <span>*</span><select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="">Select purpose</option><option>Phone screening</option><option>Application update</option><option>Interview coordination</option><option>Offer discussion</option></select></label><label>Confirmed phone number <span>*</span><input value="Demo number on file" readOnly/></label><div className="template"><p>Hi Candidate, this is Recruiter A from Scale Up Philippines. I’m contacting you regarding your application for the {callCandidate.role} role. May I call you within the next 5–10 minutes to discuss {purpose||"[purpose]"}? Please let me know if you are available. Thank you.</p><button onClick={()=>setMessageSent(true)}>{messageSent?<><Check/> Message recorded</>:<><MessageSquareText/> Send / record message</>}</button></div><div className="checks"><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> Candidate acknowledged</label><label>Expected call time <span>*</span><input type="time" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label></div><div className="modalActions"><button className="cancel" onClick={()=>setCallCandidate(null)}>Cancel</button><button className="call" disabled={!canCall}><Phone/> Start call & log result</button></div></div></div>}
  {selectedCandidate&&<div className="modalBackdrop"><div className="modal"><button className="modalClose" onClick={()=>setSelectedCandidate(null)}><X/></button><p className="eyebrow">APPLICATION DETAILS</p><h2>{selectedCandidate.name}</h2><div className="ownership"><UserRoundCheck size={18}/><p>Primary owner: <b>{selectedCandidate.owner}</b><br/>Last communication: <b>{selectedCandidate.lastContact}</b></p></div><label>Application reference<input value={selectedCandidate.id} readOnly/></label><label>Position<input value={selectedCandidate.role} readOnly/></label><label>Current status<input value={selectedCandidate.status} readOnly/></label><label>Next action<input value={`${selectedCandidate.nextAction} · ${selectedCandidate.due}`} readOnly/></label><div className="modalActions"><button className="cancel" onClick={()=>setSelectedCandidate(null)}>Close</button><button className="call" onClick={()=>{setSelectedCandidate(null);setCallCandidate(selectedCandidate)}}><Phone/> Prepare call</button></div></div></div>}
  {workflowItem&&<WorkflowModal item={workflowItem} onClose={()=>setWorkflowItem(null)}/>} 
 </div>
}

function Alert({title,count,note,kind,icon}:{title:string;count:string;note:string;kind:string;icon:React.ReactNode}){return <div className={`alert ${kind}`}><div className="alertIcon">{icon}</div><div><p>{title}</p><b>{count}</b><span>{note}</span></div><ArrowUpRight className="arrow"/></div>}
function Attention({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="attentionRow"><span>{icon}</span><div><b>{title}</b><p>{text}</p></div><ChevronDown/></div>}
function Ring(){return <div className="ring"><div><b>15</b><span>open tasks</span></div></div>}
function initials(name:string){return name.split(" ").slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function formatDate(value:string|null,fallback="No due date"){if(!value)return fallback;return new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value))}

function DemoModule({name,applications,onCandidate,onCall,onOpen}:{name:string;applications:Application[];onCandidate:(a:Application)=>void;onCall:(a:Application)=>void;onOpen:(row:string[])=>void}){
 const moduleRows:Record<string,string[][]>={
  Candidates:applications.map(a=>[a.name,a.role,a.owner,a.status]),
  Referrals:[["Demo Referral 01","Team Member A","Sales Development Representative","Recruiter A","New referral","Review today"],["Demo Referral 02","Team Member B","Medical Biller – Orthopedic","Recruiter B","Phone screening","Call tomorrow"],["Demo Referral 03","Team Member C","Property Investment Assistant","Unassigned","Awaiting review","Assign owner"]],
  Vacancies:[["Sales Development Representative","5 active applications","Open"],["Medical Biller – Orthopedic","3 active applications","Open"],["Property Investment Assistant","4 active applications","Closing applications"]],
  Interviews:[["Demo Candidate 05","Client Services Coordinator","Today · 5:00 PM","Awaiting buddy review"],["Demo Candidate 03","Property Investment Assistant","Tomorrow · 8:00 PM","Draft"]],
  Communications:[["Demo Candidate 04","Holding update","Overdue 6h","Recruiter C"],["Demo Candidate 01","Application acknowledgment","Not sent","Recruiter A"]],
  "Active Pool":[["Demo Candidate 06","Bookkeeping","Reconfirm by Aug 30","Active"],["Demo Candidate 07","Executive Assistant","Follow-up overdue","Needs update"]],
  Offers:[["Demo Candidate 08","Technical Support Specialist","Within approved range","Awaiting review"],["Demo Candidate 09","Bookkeeper","Rate hidden","Draft"]],
  "Onboarding Documents":[["Demo Candidate 10","Conditional offer","2 of 4 complete","Restricted"],["Demo Candidate 11","Onboarding","Awaiting NBI link","Restricted"]],
  "Recruitment Tasks":[["Close filled-role job posts","Lucky","Today","High"],["Review phone-screening queue","Dhem","Tomorrow","Medium"]],
  "Team Performance":[["Applications acknowledged within SLA","96%","Target 95%","On track"],["Updates sent within 48 hours","88%","Target 95%","Needs attention"]],
  Reports:[["Weekly recruitment operations","Aug 18–24","Ready","View"],["Vacancy closure audit","August","In progress","Open"]],
  "Templates & Settings":[["Pre-call availability message","Calling","Active","Edit"],["Filled-role notification","Closure","Active","Edit"]]
 };
 const headings:Record<string,string[]>={Candidates:["Candidate","Position","Owner","Status"],Referrals:["Candidate","Referred by","Position","Owner","Status","Next action"],Vacancies:["Vacancy","Pipeline","Status"],Interviews:["Candidate","Position","Schedule","Approval"],Communications:["Candidate","Purpose","Due","Owner"],"Active Pool":["Candidate","Specialty","Next check","Status"],Offers:["Candidate","Position","Rate check","Status"],"Onboarding Documents":["Candidate","Stage","Progress","Access"],"Recruitment Tasks":["Task","Owner","Deadline","Priority"],"Team Performance":["KPI","Result","Goal","Status"],Reports:["Report","Period","Status","Action"],"Templates & Settings":["Template","Workflow","Status","Action"]};
 if(name==="Application Inbox") return <section className="panel applications"><div className="panelHead"><div><h3>Application inbox</h3><p>Select any application to review its details and next action.</p></div></div><div className="tableWrap"><table><thead><tr><th>Candidate</th><th>Status</th><th>Owner</th><th>Next action</th><th>Last contact</th></tr></thead><tbody>{applications.map(a=><tr key={a.id} onClick={()=>onCandidate(a)} style={{cursor:"pointer"}}><td><div className="candidate"><span className={`person ${a.tone}`}>{a.initials}</span><div><b>{a.name}</b><small>{a.role}</small><small>{a.source} · {a.id}</small></div></div></td><td><span className="statusDot">{a.status}</span></td><td>{a.owner}</td><td><button className="action" onClick={e=>{e.stopPropagation();onCall(a)}}>{a.nextAction}<small>{a.due}</small></button></td><td>{a.lastContact}</td></tr>)}</tbody></table></div></section>;
 const rows=moduleRows[name]||[["Demo module","Sample workflow","Ready for trial","Open"]]; const cols=headings[name]||["Item","Details","Status","Action"];
 return <section className="panel applications"><div className="panelHead"><div><h3>{name}</h3><p>Select a record to open its complete workflow.</p></div><button className="primary" onClick={()=>onOpen([`New ${name} record`,"Draft","Unassigned","Open"])}><Plus size={16}/> Add demo record</button></div><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} style={{cursor:"pointer"}} onClick={()=>name==="Candidates"&&applications[i]?onCandidate(applications[i]):onOpen(row)}>{row.map((cell,j)=><td key={j}>{j===0?<b>{cell}</b>:cell}</td>)}</tr>)}</tbody></table></div></section>
}

const ratingFields=["Clarity and Coherence","Grammar and Vocabulary","Listening and Comprehension","Pronunciation","Pace and Fluency","Intonation and Emphasis","Confidence and Poise","Empathy and Friendliness","Technical Proficiency","Adaptability and Problem Solving","Fit for the Role"];

function WorkflowModal({item,onClose}:{item:{module:string;row:string[]};onClose:()=>void}){
 const [ratings,setRatings]=useState<Record<string,string>>({}); const [decision,setDecision]=useState("Pending"); const [comment,setComment]=useState(""); const [chat,setChat]=useState(["Recruitment Team: Hi! This is a secure demo conversation regarding your application.","Candidate: Thank you. I am available for the next step."]); const [message,setMessage]=useState("");
 const title=item.row[0]||item.module; const openJd=()=>window.open(`/demo-jd?position=${encodeURIComponent(item.row[1]||title)}`,"_blank","noopener,noreferrer");
 return <div className="modalBackdrop"><div className="modal" style={{maxWidth:760,maxHeight:"90vh",overflowY:"auto"}}><button className="modalClose" onClick={onClose}><X/></button><p className="eyebrow">{item.module.toUpperCase()} WORKFLOW</p><h2>{title}</h2>
  {item.module==="Vacancies"&&<><div className="ownership"><BriefcaseBusiness size={18}/><p><b>{item.row[2]||"Open"}</b><br/>{item.row[1]||"0 active applications"} currently in the pipeline.</p></div><h3>Vacancy description</h3><p>This vacancy contains the approved job description, setup, client requirements, assigned team, and closure checklist.</p><button className="full" onClick={openJd}>Open attached job description in new window</button><h3>Active candidates and progress</h3><div className="template"><p>Demo Candidate 01 — Phone screening · Recruiter A<br/>Demo Candidate 02 — Awaiting interview · Recruiter B<br/>Demo Candidate 03 — Client review · Recruitment Lead</p></div></>}
  {item.module==="Interviews"&&<><div className="ownership"><CalendarDays size={18}/><p>Buddy approver: <b>Demo Recruitment Lead</b><br/>Prepared by: Recruiter A · Interviewer: Demo Hiring Manager</p></div><label>Interview schedule<input value={item.row[2]||"To be scheduled"} readOnly/></label><label>Meeting information<input value="Google Meet · Candidate and client confirmed" readOnly/></label><button className="full" onClick={openJd}>Open attached job description in new window</button><h3>Internal interview scorecard</h3>{ratingFields.map(field=><label key={field}>{field}<select value={ratings[field]||""} onChange={e=>setRatings({...ratings,[field]:e.target.value})}><option value="">Select rating</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {n<3?"Needs improvement":n===3?"Meets expectations":n===4?"Strong":"Excellent"}</option>)}</select></label>)}<label>Comments and recommendation<textarea value={comment} onChange={e=>setComment(e.target.value)} rows={3}/></label><label>Possible other positions<input placeholder="Mandatory if not selected"/></label><label>Endorsement<select><option>Strongly Recommend</option><option>Recommend</option><option>Neutral</option><option>Do Not Recommend</option></select></label><label>Final result<select value={decision} onChange={e=>setDecision(e.target.value)}><option>Pending</option><option>Pass</option><option>Fail</option><option>No-show</option></select></label><div className="modalActions"><a className="cancel" href="https://docs.google.com/forms/d/e/1FAIpQLSfsSzp5z-Iqe3ffadcxF54oVTBGTX9eE2Umh_OvnHAfbPgWKg/viewform" target="_blank" rel="noreferrer">View original form</a><button className="call" onClick={()=>alert(`Demo evaluation saved: ${decision}`)}><Check/> Save rating</button></div></>}
  {item.module==="Communications"&&<><div className="ownership"><MessageSquareText size={18}/><p>Secure candidate thread · Demo expiry: <b>60 days</b><br/>Email notification enabled; SMS can be added later.</p></div><div className="template">{chat.map((m,i)=><p key={i}>{m}</p>)}</div><label>Reply<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="Write a secure message…"/></label><button className="full" disabled={!message.trim()} onClick={()=>{setChat([...chat,`Recruitment Team: ${message}`]);setMessage("")}}>Send demo reply</button></>}
  {item.module==="Active Pool"&&<><div className="ownership"><Users size={18}/><p>Interest reconfirmation due every <b>30 days</b>. Current state: {item.row[3]||"Active"}.</p></div><label>Availability<select><option>Available immediately</option><option>Available with notice</option><option>Not currently available</option></select></label><label>Preferred roles<input defaultValue={item.row[1]||"Open to matching roles"}/></label><label>Next reconfirmation date<input type="date"/></label><button className="full" onClick={()=>alert("Demo active-pool update saved")}>Save pool update</button></>}
  {item.module==="Offers"&&<><div className="ownership"><ShieldCheck size={18}/><p>Restricted offer workspace · Status: <b>{item.row[3]||"Draft"}</b></p></div><label>Candidate<input value={item.row[0]} readOnly/></label><label>Position<input value={item.row[1]||"Position"} readOnly/></label><label>Rate compliance<input value={item.row[2]||"Pending authorized review"} readOnly/></label><label>Approver<select><option>Demo Administrator</option><option>Demo Recruitment Lead</option></select></label><label>Proposed start date<input type="date"/></label><button className="full" onClick={()=>alert("Demo offer submitted for approval")}>Submit for approval</button></>}
  {!['Vacancies','Interviews','Communications','Active Pool','Offers'].includes(item.module)&&<><div className="ownership"><Check size={18}/><p>This {item.module.toLowerCase()} record is open and ready for review.</p></div>{item.row.slice(1).map((value,i)=><label key={i}>Detail {i+1}<input defaultValue={value}/></label>)}<button className="full" onClick={()=>alert("Demo record saved")}>Save demo changes</button></>}
 </div></div>
}
